apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/created-by: contour-global-ratelimit-operator
    app.kubernetes.io/part-of: contour-global-ratelimit-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
spec:
  ports:
  - name: xds
    port: 18000
    protocol: TCP
    targetPort: xds
  selector:
    control-plane: controller-manager